### PR TITLE
fix quiz.py

### PR DESCRIPTION
**Pull request by drvnprgrmr**
The issue was the indentation level. I've applied consistent indentation throughout the project.

### CODE REVIEW

**Comment by Tijesunimi004** [comment]
Thanks mate I appreciate

**Comment by drvnprgrmr** [comment]
Some extra advice... 
- Use the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) 
- Read up on PEP8 [here](https://realpython.com/python-pep8/) and [here](https://realpython.com/python-pep8/)
- Always use a `.gitignore` file in your projects

**Comment by drvnprgrmr** [comment]
P.S. there are some other issues with the main loop of your code (it doesn't differentiate btw numbers and always runs the first one). Try debugging it by printing the result of `choice` and `choice.isdecimal()` and see if you can come up with a fix. :)

**Review by Tijesunimi004 — APPROVED** [review]
Nothing else

**Comment by drvnprgrmr** [comment]
Do `git revert 3870b51`

**Pull request merged**
